- README.md
- cloudformation.yaml
- docs/README.md
> Issue 3.dockter.1

- cloudformation.yaml
> #3 Update default

- CHANGELOG.md
- cloudformation.yaml
> #3 Prepare for version

- cloudformation.yaml
> #8 email HTML updates

- cloudformation.yaml
> Issue 13.ron 0

- cloudformation.yaml
> #15 updated EFS lamba function

- cloudformation.yaml
> #15 added wait for EFS to be ready

- cloudformation.yaml
> Issue 16.ron.0

- cloudformation.yaml
> 23 updated admin email

- cloudformation.yaml
> 25 set load balancer name to support mixed case

- cloudformation.yaml
> #27 removed private subnet from sshd services

- cloudformation.yaml
> #29 updated memory for key services

- cloudformation.yaml
> #29 updated cpu for key services

- cloudformation.yaml
> #40 moved image definitions to constants

- cloudformation.yaml
> #42 removed senzing data mount points and volumes

- cloudformation.yaml
> #35 added new cidr block rules and language.

- cloudformation.yaml
> #37 updated image and senzing version

- CHANGELOG.md
- cloudformation.yaml
…nhancements
Issue number: #32  & #33 & #34 
- Updated security to match what was done for marketplace
- added WSS support for the web app
- rearranged parameters to match marketplace
> Issue 32.ron.0

- cloudformation.yaml
> #49 added SENZING_ENGINE_CONFIGURATION_JSON

- CHANGELOG.md
- cloudformation.yaml
and added new senzing versions.
Issue number: #62
???
???
> #62 removed erroneous web condition from passrole policy 

- .github/workflows/copy-to-s3.yaml
Issue number: #64 
It was copying to the wrong location
> copying cloudformation.yaml to the correct bucket

- .github/workflows/copy-to-s3.yaml
Issue number: #66 
Files need to be public on S3
> Making files copied to S3 public

- cloudformation.yaml
> #68 updated cognito email

- CHANGELOG.md
- cloudformation.yaml
> #70 updated yum container version

- CHANGELOG.md
- cloudformation.yaml
> Issue 72.ron.0

- CHANGELOG.md
- cloudformation.yaml
> Issue 74.ron.0

- CHANGELOG.md
- cloudformation.yaml
> #76 updated image versions

- CHANGELOG.md
- cloudformation.yaml
- cloudformationV2.yaml
- docs/README.md
> Issue 80.ron.0

- CONTRIBUTING.md
- README.md
- cloudformation.yaml
- cloudformationV2.yaml
- docs/README.md
> #79 Migrate from master to main

- README.md
> #82 updated readme

- README.md
> #85 updated readme

- CHANGELOG.md
- README.md
- cloudformation.yaml
> #87 updated resource names

- README.md
> #89 updated readme

- cloudformation.yaml
- docs/README.md
> Issue 39.ron.0

- CHANGELOG.md
- cloudformation.yaml
> #95 added suffix to UserPoolDomain

- CHANGELOG.md
- cloudformation.yaml
> #92 updated image and senzing versions

- CHANGELOG.md
- cloudformation.yaml
> #102 added engine config support for single database
